FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY server/package*.json server/
COPY worker/package*.json worker/
COPY scheduler/package*.json scheduler/
COPY client/package*.json client/
COPY tsconfig.json ./
RUN npm ci --ignore-scripts
RUN npm install @rollup/rollup-linux-x64-musl --no-save --workspace=client
COPY client client
RUN npm run build --workspace=client

FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime
COPY --from=build /app/client/dist /usr/share/nginx/html
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
